stages:
  process:
    cmd: python3 process_data.py
    deps:
    - process_data.py
    outs:
    - data_processed_train.csv
  train:
    cmd: python3 train.py
    deps:
    - train.py
    - data_processed_train.csv
    outs:
    - permutate_feature_importance_top_10.png
    metrics:
    - metrics.json:
        cache: false
