version: "3.9"

services:
  server:
    restart: always
    build: mlflow/
    ports:
      - 5000:5000
    volumes:
      - ./volume:/volume
    environment:
      #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      #- AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      #- AWS_DEFAULT_REGION=eu-central-1
  client:
    restart: always
    build: client/
    volumes:
      - ./src:/src
      - ./volume:/volume
    network_mode: host
    environment:
      #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      #- AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      #- AWS_DEFAULT_REGION=eu-central-1
    depends_on:
      - server
volumes:
  volume: