version: "3.9"

services:
  server:
    build: mlflow/
    ports:
      - 7777:7777
    volumes:
      - vol:/volume

  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    volumes:
      - ./src:/src
      - vol:/volume
    network_mode: host
    depends_on:
      - server

volumes:
     vol:
