version: "3.9"

services:
  server:
    build: 
      context: ./mlflow/
      dockerfile: Dockerfile
    ports:
      - 7777:7777
    expose: 
      - 7777  
    volumes:
      - ./volume:/home/new_user/volume
    command: bash -c "cd volume && mlflow server --host 0.0.0.0:7777" 
    restart: on-failure
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - ./volume:/home/new_user/volume
    depends_on:
      - server
    command: bash -c "export GIT_PYTHON_REFRESH=quiet && cd volume && python src/train.py"  

