name: autoblack_push
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
            ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v1
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install libraries
        run: pip install -r mlflow_hw/client/requirements.txt
      - name: Run Pylint
        run: pylint $(git ls-files '*.py') --fail-under=5
      - name: Run black
        run: black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black .
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "Format Python code with psf/black push"
          git push  # --force origin HEAD:$GITHUB_REF