name: data_governance
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          cd data_governance_hw
          pwd
          pip install -r requirements.txt
          dvc pull train.csv
          pytest tests.py
          dvc repro
          git fetch --prune
          dvc metrics diff --show-md main > report.md
          # Add figure to the report
          echo "## Validating results by region"
          cml-send-comment report.md